spring:
  application:
    name: jetz-server

  datasource:
    url: jdbc:mysql://localhost:3306/jetz?serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
